version: '2.4'

services:

  traefik:
    image: traefik:alpine
    ports:
      - "80:80
      - "443:443"
      - "8080:8080"
    labels:
      - traefik.backend=traefik
      - traefik.frontend.rule=Host:traefik.example.org
      - traefik.port=8080
      - traefik.enable=true
      # - traefik.frontend.auth.basic.users=admin:$$2y$$05$$mLR8hPAoXy0VJjOjqFkM6.0VJP7q1HwoQi5qCCLe3WWvGKXGMv9q6
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/traefik.toml:/etc/traefik/traefik.toml

  nginx:
    image: nginx:alpine
    labels:
      - traefik.backend=nginx
      - traefik.frontend.rule=Host:nginx.example.com,www.example.com,example.com
      - traefik.port=80
      - traefik.enable=true
    # volumes:
    #   - ${PWD}/nginx-index.html:/usr/share/nginx/html/index.html

  apache:
    image: httpd:alpine
    labels:
      - traefik.backend=apache
      - traefik.frontend.rule=Host:apache.example.net,www.example.net,example.net
      - traefik.port=80
      - traefik.enable=true
    # volumes:
    #   - ${PWD}/apache-index.html:/usr/local/apache2/htdocs/index.html

  mysqldb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD="root"
    labels:
      - traefik.enable=false
