version: '2.4'

services:

  traefik:
    image: traefik:alpine
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    labels:
      - traefik.backend=traefik
      - traefik.frontend.rule=Host:traefik.example.org
      - traefik.port=8080
      - traefik.enable=true
      - traefik.frontend.auth.basic.users=admin:$apr1$z3XCES5c$SXXWC/h3sYzvjptzWg7Cf/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/traefik.toml:/etc/traefik/traefik.toml
      - ${PWD}/acme.json:/acme.json

  nginx:
    image: nginx:alpine
    labels:
      - traefik.backend=nginx
      - traefik.frontend.rule=Host:nginx.example.com,www.example.com,example.com
      - traefik.port=80
      - traefik.enable=true
    # volumes:
    #   - ${PWD}/nginx-index.html:/usr/share/nginx/html/index.html
