defaultEntryPoints = ["http", "https"]
logLevel = "INFO"

# sendAnonymousUsage = true

[docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false

[api]
dashboard = true
entrypoint = "dashboard"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"

  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

  [entryPoints.dashboard]
  address = ":8080"
    [entryPoints.dashboard.auth.basic]
    users = ["admin:$apr1$z3XCES5c$SXXWC/h3sYzvjptzWg7Cf/"]

[acme]
acmeLogging = true
email = "john@gmail.com"
storage = "acme.json"

# CA server to use.
# caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
entryPoint = "https"
onHostRule = true
  [acme.httpChallenge]
    entryPoint = "http"

[[acme.domains]]
  main = "localhost"
